### ISSUE TITLE
Automatically compile style.css

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/datacenter_skeleton#3]
Upon installation, automatically compile style.less into style.css

**Comment by PhantomWatson** [comment]
I haven't been able to find a PHP LESS compiler that isn't [abandoned](https://github.com/leafo/lessphp) or [quite buggy](https://github.com/oyejorge/less.php). :(

**Comment by ericadeefox** [comment]
I found one for Cake 2.x: https://github.com/BradCrumb/lesscompiler

Would it be worth branching this one and upgrading it to 3.x ourselves?

**Comment by PhantomWatson** [comment]
Both use [oyejorge/less.php](https://github.com/oyejorge/less.php) for compiling, which with its 77 open issues (a couple of them suggesting PHP 7 incompatibility) and half a year since any substantial updates, I'm hesitant to depend on.

[This guy](https://github.com/kylekatarnls/less.php) seems to have an active fork of the same project, though.

Automatically compiling LESS with PHP when the skeleton app is installed isn't a big deal to me, and I'd happily abandon the idea for now. We'll probably always be recompiling LESS via Node anyway, so running `lessc webroot/css/styles.less` once a new skeleton app gets installed seems like a way simpler route than setting up one-time automatic PHP compiling.
